version: "3"
services:
  certification_entity:
    image: cert_entity
    ports:
      - "8080:8080"
    environment:
      - API_CERTIFICATE_ENDPOINT=https://ci-cd-manager.5gasp.eu/certification-entity/certificate
