# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CertCreated(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, certificate: str=None):  # noqa: E501
        """CertCreated - a model defined in Swagger

        :param certificate: The certificate of this CertCreated.  # noqa: E501
        :type certificate: str
        """
        self.swagger_types = {
            'certificate': str
        }

        self.attribute_map = {
            'certificate': 'certificate'
        }
        self._certificate = certificate

    @classmethod
    def from_dict(cls, dikt) -> 'CertCreated':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CertCreated of this CertCreated.  # noqa: E501
        :rtype: CertCreated
        """
        return util.deserialize_model(dikt, cls)

    @property
    def certificate(self) -> str:
        """Gets the certificate of this CertCreated.

        URL pointing to the certificate  # noqa: E501

        :return: The certificate of this CertCreated.
        :rtype: str
        """
        return self._certificate

    @certificate.setter
    def certificate(self, certificate: str):
        """Sets the certificate of this CertCreated.

        URL pointing to the certificate  # noqa: E501

        :param certificate: The certificate of this CertCreated.
        :type certificate: str
        """

        self._certificate = certificate
