# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ServerInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, version: str=None):  # noqa: E501
        """ServerInfo - a model defined in Swagger

        :param name: The name of this ServerInfo.  # noqa: E501
        :type name: str
        :param version: The version of this ServerInfo.  # noqa: E501
        :type version: str
        """
        self.swagger_types = {
            'name': str,
            'version': str
        }

        self.attribute_map = {
            'name': 'name',
            'version': 'version'
        }
        self._name = name
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'ServerInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServerInfo of this ServerInfo.  # noqa: E501
        :rtype: ServerInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ServerInfo.


        :return: The name of this ServerInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ServerInfo.


        :param name: The name of this ServerInfo.
        :type name: str
        """

        self._name = name

    @property
    def version(self) -> str:
        """Gets the version of this ServerInfo.


        :return: The version of this ServerInfo.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this ServerInfo.


        :param version: The version of this ServerInfo.
        :type version: str
        """

        self._version = version
