openapi: 3.0.3
info:
  title: Certification Entity API
  description: REST API of the 5GASP Certification Entity
  version: "0.5"
servers:
- url: /
tags:
- name: certification
  description: ""
paths:
  /:
    get:
      tags:
      - certification
      summary: Get server info
      operationId: get_server_info
      responses:
        "200":
          description: Basic server info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerInfo'
      x-openapi-router-controller: swagger_server.controllers.certification_controller
  /certificate:
    get:
      tags:
      - certification
      summary: Get the certificate for a testing (identified by the test_id)
      operationId: get_cert
      parameters:
      - name: test_id
        in: query
        required: true
        style: form
        explode: true
        schema:
          title: test_id
          type: integer
      - name: access_token
        in: query
        required: true
        style: form
        explode: true
        schema:
          title: access_token
          type: string
      responses:
        "200":
          description: Certificate is available
          content:
            application/pdf:
              schema:
                type: string
                description: Certificate as PDF
                format: binary
                x-content-type: application/pdf
        "403":
          description: Access token is not correct
        "404":
          description: There is no certificate for this test_id
      x-openapi-router-controller: swagger_server.controllers.certification_controller
    post:
      tags:
      - certification
      summary: Create a certificate for a testing (identified by the test_id)
      operationId: create_cert
      requestBody:
        description: Create a certificate
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCert'
        required: true
      responses:
        "201":
          description: Certificate or intermediary result has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertCreated'
        "401":
          description: Login required or wrong credentials
        "404":
          description: Could not gather data or data missing
        "409":
          description: Certificate has already been created
        "500":
          description: Could not save certificate
      security:
      - basicAuth: []
      x-openapi-router-controller: swagger_server.controllers.certification_controller
  /test_cases:
    get:
      tags:
      - certification
      summary: "Get the list of mandatory and conditional mandatory test cases for\
        \ a specified set of test conditions. If no conditions are specified, the\
        \ list contains only mandatory test cases."
      operationId: get_test_cases
      parameters:
      - name: test_bed
        in: query
        description: Test bed ID for which to get the test cases
        required: true
        style: form
        explode: true
        schema:
          title: test_bed
          type: string
        example: testbed_itav
      - name: test_conditions
        in: query
        description: |
          List of test conditions delimited by comma. The mapping is as follows: 1) NEF support, 2) Location-based app, 3) Mobility-based app, 4) Premium QoS app, 5) Deployment type VM, 6) Deployment type Container, 7) Data plane app, 8) Application layer traffic, 9) Scalable on the number of users, 10) Scalable on the number of Network Application instances.
        required: false
        style: form
        explode: true
        schema:
          title: test_conditions
          type: string
        example: "1,2,3"
      responses:
        "200":
          description: Test case list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestCaseList'
        "400":
          description: Test bed ID incorrect or list of conditions formatted incorrectly
        "404":
          description: Could not fetch test case data
      x-openapi-router-controller: swagger_server.controllers.certification_controller
components:
  schemas:
    ServerInfo:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
      example:
        name: name
        version: version
    CreateCert:
      required:
      - access_token
      - app_author
      - app_name
      - app_version
      - service_order
      - test_id
      type: object
      properties:
        test_id:
          type: integer
          description: test_id from CI/CD Manager to query test details and results
          format: int64
        access_token:
          type: string
          description: access_token from CI/CD Manager for test_id
        app_name:
          type: string
          description: Name of the Network App
        app_version:
          type: string
          description: Version of the Network App
        app_author:
          type: string
          description: Author or who registered the Network App
        service_order:
          type: string
          description: Link to the service order of the Network App on NODS
    CertCreated:
      type: object
      properties:
        certificate:
          type: string
          description: URL pointing to the certificate
      example:
        certificate: certificate
    TestCaseList:
      type: object
      properties:
        test_cases:
          type: array
          description: List of test case IDs
          items:
            type: integer
      example:
        test_cases:
        - 0
        - 0
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      x-basicInfoFunc: swagger_server.controllers.authorization_controller.check_basicAuth
